[package]
name = "iotdb"
version = "0.0.3"
edition = "2018"
license = "Apache-2.0"
readme = "README.md"
authors = ["francis-du <francis@francisdu.com>"]
repository = "https://github.com/francis-du/iotdb-rs"
documentation = "https://docs.rs/iotdb"
description = "Rust client for Apache IotDB"
keywords = ["api", "iotdb","thrift"]

[dependencies]
prettytable-rs = "^0.8"
chrono = "0.4.19"
thrift = "0.13"
log = "0.4.13"