[package]
name = "iotdb-rs"
version = "0.0.1"
edition = "2018"
license = "Apache-2.0"
license-file = "LICENSE"
readme = "README.md"
authors = ["francis-du <francis@francisdu.com>"]
repository = "https://github.com/francis-du/iotdb-rs"
documentation = "https://docs.rs/iotdb-rs/"
description = "Rust client for Apache IotDB"
keywords = ["api", "iotdb","thrift"]

[dependencies]
prettytable-rs = "^0.8"
chrono = "0.4.19"
thrift = "0.13"
log = "0.4.13"

[package.metadata.docs.rs]
features = ["doc"]
targets = ["x86_64-unknown-linux-gnu"]